spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: spring_session
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '60000'
    url: jdbc:postgresql://localhost:8095/postgres
    password: spring_session
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: spring_session_demo
